[[headers]]
for = "/fonts/*.woff"
[headers.values]
Access-Control-Allow-Origin = "gpcshopian.in"
Content-Type = "application/font-woff"
[[headers]]
for = "/fonts/*.ttf"
[headers.values]
Access-Control-Allow-Origin = "gpcshopian.in"
Content-Type = "application/font-ttf"